### ISSUE TITLE
[Xcode 11.2] Compile error: "Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler:..."

### ISSUE THREAD

**Issue by bytethenoodle** [CANDY-HOUSE/SDK_iOS_Sesame_Demo#3]
Using Xcode 11.2, error is encountered below when compiling:

"Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: .../SesameSDK.framework/Modules/SesameSDK.swiftmodule/arm64-apple-ios.swiftmodule"

**Comment by Jerming** [comment]
Hi @bytethenoodle thanks for the feedback.
The issue has been fixed in today's master release.
Sincerely,

**Comment by bytethenoodle** [comment]
Thank you very much 🙇🏻‍♂️
