### ISSUE TITLE
Couldn't build app with Xcode 11.4

### ISSUE THREAD

**Issue by key** [CANDY-HOUSE/SDK_iOS_Sesame_Demo#4]
Hi, I tried to build this app with Xcode 11.4. Sesame SDK seems incompatible with Swift 5.2. What should I do?

```
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /Users/key/Work/SDK_iOS_Sesame_Demo/sdk/SesameSDK.framework/Modules/SesameSDK.swiftmodule/arm64-apple-ios.swiftmodule
```

**Comment by Jerming** [comment]
Hi @key 
We just released 1.1.1(1) which is compatible with Xcode 11.4
Please give it a try. Thank you.
